import type { Config } from 'tailwindcss'
import daisyui from 'daisyui'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  
  theme: {
    extend: {
      fontFamily: {
        mono: ['var(--font-space-mono)', 'Space Mono', 'monospace'],
        pixel: ['var(--font-ibm-plex)', 'IBM Plex Mono', 'monospace'],
      },
      colors: {
        background: 'hsl(var(--b1) / <alpha-value>)',
        'background-secondary': 'hsl(var(--b2) / <alpha-value>)',
        foreground: 'hsl(var(--bc) / <alpha-value>)',
        'foreground-muted': 'hsl(var(--bc) / 0.7)',
        'muted-foreground': 'hsl(var(--bc) / 0.65)',
        primary: {
          DEFAULT: 'hsl(var(--p) / <alpha-value>)',
          foreground: 'hsl(var(--pc) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--s) / <alpha-value>)',
          foreground: 'hsl(var(--sc) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'hsl(var(--a) / <alpha-value>)',
          foreground: 'hsl(var(--ac) / <alpha-value>)',
          secondary: 'hsl(var(--p) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'hsl(var(--b3) / <alpha-value>)',
          light: 'hsl(var(--b3) / <alpha-value>)',
        },
        card: {
          DEFAULT: 'hsl(var(--b2) / <alpha-value>)',
          hover: 'hsl(var(--b1) / <alpha-value>)',
        },
        muted: 'hsl(var(--b2) / <alpha-value>)',
        destructive: 'hsl(var(--er) / <alpha-value>)',
        success: 'hsl(var(--su) / <alpha-value>)',
        warning: 'hsl(var(--wa) / <alpha-value>)',
        info: 'hsl(var(--in) / <alpha-value>)',
      },
      keyframes: {
        'slide-fade': {
          '0%': { opacity: '0', transform: 'translateX(-24px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'sticker-in': {
          '0%': {
            opacity: '0',
            transform: 'translateY(24px) translateX(-18px) rotate(-4deg)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0) translateX(0) rotate(0deg)',
          },
        },
        float: {
          '0%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        'slide-fade':
          'slide-fade 300ms cubic-bezier(0.2, 0.8, 0.2, 1) backwards',
        'sticker-in': 'sticker-in 500ms cubic-bezier(0.2, 0.8, 0.2, 1) backwards',
        float: 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      'forest',
      'synthwave',
      'night',
      'cyberpunk',
      'black',
      {
        moss: {
          primary: '#4f7f3b',
          'primary-content': '#f7f8f3',
          secondary: '#6aa84f',
          'secondary-content': '#132014',
          accent: '#2f6f5a',
          'accent-content': '#ecf4ef',
          neutral: '#1f261d',
          'neutral-content': '#f8fafc',
          'base-100': '#f7f8f3',
          'base-200': '#eef1e6',
          'base-300': '#e2e7da',
          'base-content': '#1d221a',
          info: '#4a8ecf',
          'info-content': '#f8fafc',
          success: '#2f9d6a',
          'success-content': '#f8fafc',
          warning: '#e0a845',
          'warning-content': '#1f1400',
          error: '#d35b5b',
          'error-content': '#fff5f5',
        },
        pearl: {
          primary: '#3b5ccc',
          'primary-content': '#f8fafc',
          secondary: '#64748b',
          'secondary-content': '#f8fafc',
          accent: '#4b7bdc',
          'accent-content': '#f8fafc',
          neutral: '#1f2430',
          'neutral-content': '#f8fafc',
          'base-100': '#fbfbfc',
          'base-200': '#f1f4f8',
          'base-300': '#e3e7ee',
          'base-content': '#1f2430',
          info: '#3b82f6',
          'info-content': '#f8fafc',
          success: '#16a34a',
          'success-content': '#ecfdf5',
          warning: '#f59e0b',
          'warning-content': '#2b1900',
          error: '#ef4444',
          'error-content': '#fff5f5',
        },
        aurora: {
          primary: '#7c3aed',
          'primary-content': '#fdfcff',
          secondary: '#ec4899',
          'secondary-content': '#fdfcff',
          accent: '#38bdf8',
          'accent-content': '#0b1120',
          neutral: '#241c33',
          'neutral-content': '#f8fafc',
          'base-100': '#faf7ff',
          'base-200': '#f2ecff',
          'base-300': '#e7ddff',
          'base-content': '#221a2f',
          info: '#0ea5e9',
          'info-content': '#f0f9ff',
          success: '#22c55e',
          'success-content': '#f0fdf4',
          warning: '#f59e0b',
          'warning-content': '#2b1900',
          error: '#ef4444',
          'error-content': '#fff5f5',
        },
        skyline: {
          primary: '#0891b2',
          'primary-content': '#ecfeff',
          secondary: '#14b8a6',
          'secondary-content': '#ecfeff',
          accent: '#38bdf8',
          'accent-content': '#0b1120',
          neutral: '#1f2a33',
          'neutral-content': '#f8fafc',
          'base-100': '#f4fbff',
          'base-200': '#e8f3fb',
          'base-300': '#dbe9f4',
          'base-content': '#10232b',
          info: '#0ea5e9',
          'info-content': '#f0f9ff',
          success: '#16a34a',
          'success-content': '#f0fdf4',
          warning: '#f59e0b',
          'warning-content': '#2b1900',
          error: '#ef4444',
          'error-content': '#fff5f5',
        },
        prism: {
          primary: '#f97316',
          'primary-content': '#fff7ed',
          secondary: '#a855f7',
          'secondary-content': '#fdf4ff',
          accent: '#06b6d4',
          'accent-content': '#ecfeff',
          neutral: '#2b1f2f',
          'neutral-content': '#f8fafc',
          'base-100': '#fff8f3',
          'base-200': '#fcefe6',
          'base-300': '#f3e0d6',
          'base-content': '#2b1f2f',
          info: '#3b82f6',
          'info-content': '#eff6ff',
          success: '#16a34a',
          'success-content': '#f0fdf4',
          warning: '#f59e0b',
          'warning-content': '#2b1900',
          error: '#ef4444',
          'error-content': '#fff5f5',
        },
        white: {
          primary: '#111827',
          'primary-content': '#f9fafb',
          secondary: '#6b7280',
          'secondary-content': '#f9fafb',
          accent: '#2563eb',
          'accent-content': '#eff6ff',
          neutral: '#111827',
          'neutral-content': '#f9fafb',
          'base-100': '#ffffff',
          'base-200': '#f3f4f6',
          'base-300': '#e5e7eb',
          'base-content': '#111827',
          info: '#3b82f6',
          'info-content': '#eff6ff',
          success: '#16a34a',
          'success-content': '#f0fdf4',
          warning: '#f59e0b',
          'warning-content': '#2b1900',
          error: '#ef4444',
          'error-content': '#fff5f5',
        },
      },
    ],
  },
}

export default config
