import type { LayoutPreset, SceneObject } from './homeCanvasTypes'

const desktopObjects: SceneObject[] = [
  {
    id: 'card-primary',
    kind: 'card',
    top: '18%',
    left: '56%',
    rotate: 2,
    scale: 1,
    lane: 'context',
    size: 'lg',
    variant: 'primary',
    cardIndex: 0,
    group: 'right',
    zIndex: 30,
  },
  {
    id: 'card-secondary',
    kind: 'card',
    top: '54%',
    left: '63%',
    rotate: -3,
    scale: 0.98,
    lane: 'context',
    size: 'md',
    variant: 'secondary',
    cardIndex: 1,
    group: 'right',
    zIndex: 28,
  },
  {
    id: 'card-tertiary',
    kind: 'card',
    top: '32%',
    left: '74%',
    rotate: 5,
    scale: 0.94,
    lane: 'context',
    size: 'sm',
    variant: 'secondary',
    cardIndex: 2,
    group: 'right',
    zIndex: 24,
  },
  {
    id: 'chip-1',
    kind: 'chip',
    top: '14%',
    left: '10%',
    rotate: -2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: 'calm 😌 is a performance feature 😙😝',
    group: 'left',
    zIndex: 18,
    treatment: 'solid',
  },
  {
    id: 'chip-2',
    kind: 'chip',
    top: '56%',
    left: '12%',
    rotate: 3,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'secondary',
    label: 'boring code 🥱, interesting results 💅✨',
    group: 'left',
    zIndex: 17,
    treatment: 'outline',
  },
  {
    id: 'chip-3',
    kind: 'chip',
    top: '38%',
    left: '36%',
    rotate: -3,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: "if it's confusing 🤔, it's unfinished ✨💅",
    group: 'center',
    zIndex: 16,
    treatment: 'glass',
  },
  {
    id: 'chip-4',
    kind: 'chip',
    top: '18%',
    left: '64%',
    rotate: 2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'secondary',
    label: 'i hate fragile systems 😤😒',
    group: 'right',
    zIndex: 16,
    treatment: 'solid',
  },
  {
    id: 'chip-5',
    kind: 'chip',
    top: '68%',
    left: '48%',
    rotate: -2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: '👀 yes, i ✨ obsessed ✨ over this 😭😭',
    group: 'center',
    zIndex: 15,
    treatment: 'easter-egg',
  },
]

const tabletObjects: SceneObject[] = [
  {
    id: 'card-primary',
    kind: 'card',
    top: '22%',
    left: '50%',
    rotate: 2,
    scale: 1,
    lane: 'context',
    size: 'lg',
    variant: 'primary',
    cardIndex: 0,
    group: 'right',
    zIndex: 28,
  },
  {
    id: 'card-secondary',
    kind: 'card',
    top: '58%',
    left: '56%',
    rotate: -2,
    scale: 0.96,
    lane: 'context',
    size: 'md',
    variant: 'secondary',
    cardIndex: 1,
    group: 'right',
    zIndex: 26,
  },
  {
    id: 'card-tertiary',
    kind: 'card',
    top: '36%',
    left: '70%',
    rotate: 4,
    scale: 0.94,
    lane: 'context',
    size: 'sm',
    variant: 'secondary',
    cardIndex: 2,
    group: 'right',
    zIndex: 24,
  },
  {
    id: 'chip-1',
    kind: 'chip',
    top: '16%',
    left: '8%',
    rotate: -3,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: 'calm 😌 is a performance feature 😙😝',
    group: 'left',
    zIndex: 16,
    treatment: 'solid',
  },
  {
    id: 'chip-2',
    kind: 'chip',
    top: '68%',
    left: '10%',
    rotate: 2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'secondary',
    label: 'boring code 🥱, interesting results 💅✨',
    group: 'left',
    zIndex: 15,
    treatment: 'outline',
  },
  {
    id: 'chip-3',
    kind: 'chip',
    top: '44%',
    left: '14%',
    rotate: -2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: "if it's confusing 🤔, it's unfinished ✨💅",
    group: 'left',
    zIndex: 14,
    treatment: 'glass',
  },
  {
    id: 'chip-4',
    kind: 'chip',
    top: '26%',
    left: '66%',
    rotate: 3,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'secondary',
    label: 'i hate fragile systems 😤😒',
    group: 'right',
    zIndex: 14,
    treatment: 'solid',
  },
  {
    id: 'chip-5',
    kind: 'chip',
    top: '78%',
    left: '48%',
    rotate: -2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: '👀 yes, i ✨ obsessed ✨ over this 😭😭',
    group: 'center',
    zIndex: 13,
    treatment: 'easter-egg',
  },
]

const mobileObjects: SceneObject[] = [
  {
    id: 'card-primary',
    kind: 'card',
    top: '52%',
    left: '8%',
    rotate: 1,
    scale: 1,
    lane: 'context',
    size: 'lg',
    variant: 'primary',
    cardIndex: 0,
    group: 'center',
    zIndex: 22,
  },
  {
    id: 'card-secondary',
    kind: 'card',
    top: '68%',
    left: '40%',
    rotate: -2,
    scale: 0.96,
    lane: 'context',
    size: 'md',
    variant: 'secondary',
    cardIndex: 1,
    group: 'center',
    zIndex: 20,
  },
  {
    id: 'card-tertiary',
    kind: 'card',
    top: '34%',
    left: '56%',
    rotate: 3,
    scale: 0.92,
    lane: 'context',
    size: 'sm',
    variant: 'secondary',
    cardIndex: 2,
    group: 'right',
    zIndex: 18,
  },
  {
    id: 'chip-1',
    kind: 'chip',
    top: '16%',
    left: '10%',
    rotate: -2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: 'calm 😌 is a performance feature 😙😝',
    group: 'left',
    zIndex: 14,
    treatment: 'solid',
  },
  {
    id: 'chip-2',
    kind: 'chip',
    top: '76%',
    left: '12%',
    rotate: 2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'secondary',
    label: 'boring code 🥱, interesting results 💅✨',
    group: 'left',
    zIndex: 13,
    treatment: 'outline',
  },
  {
    id: 'chip-3',
    kind: 'chip',
    top: '36%',
    left: '14%',
    rotate: -3,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'primary',
    label: '👀 yes, i ✨ obsessed ✨ over this 😭😭',
    group: 'left',
    zIndex: 12,
    treatment: 'easter-egg',
  },
  {
    id: 'chip-4',
    kind: 'chip',
    top: '28%',
    left: '52%',
    rotate: 2,
    scale: 1,
    lane: 'ambient',
    size: 'md',
    variant: 'secondary',
    label: 'i hate fragile systems 😤😒',
    group: 'right',
    zIndex: 11,
    treatment: 'solid',
  },
]

export const layoutObjects: Record<LayoutPreset, SceneObject[]> = {
  desktop: desktopObjects,
  tablet: tabletObjects,
  mobile: mobileObjects,
}

export const overlayLinks = [
  { href: '/projects', label: 'Projects' },
  { href: '/products', label: 'Products' },
  { href: '/about', label: 'About' },
]
